---
services:
  web:
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/web-app
  prod:
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
