name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build . --target production --tag ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
          docker push ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA

      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: 3.5.0 # default is latest

      - name: Push Helm Chart
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login --username ${{ github.repository_owner }} --password-stdin https://ghcr.io
          helm chart save ${{ github.workspace }}/.deployment/helm-chart/ ghcr.io/${{ github.repository }}-helm-chart:${{ github.sha }}
          helm chart push ghcr.io/${{ github.repository }}-helm-chart:${{ github.sha }}
